### ISSUE TITLE
Does not compile with the latest Go (r57.1)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [llgcode/draw2d#2]
```
What steps will reproduce the problem?
1. Try to build the library
2. Get the error: interpreter.go:62: too many arguments in call to os.Open

What version of the product are you using? On what operating system?

krasin@krasin7:~/go/go$ hg identify
95d2ce135523 (release-branch.r57) release/release.r57.1


Please provide any additional information below.

Running gofix solves the problem:

krasin@krasin7:~/go/go/src/pkg/draw2d.googlecode.com/hg$ gofix *
AUTHORS:1:1: expected 'package', found 'IDENT' Laurent
cmd/gettingStarted.go:19:30: rewrote os.Open with O_CREATE but not O_TRUNC to 
os.Create
cmd/gettingStarted.go:19:12: rewrote os.Open to os.Create with permission not 
0666
cmd/gettingStarted.go: fixed osopen
cmd/testandroid.go:43:30: rewrote os.Open with O_CREATE but not O_TRUNC to 
os.Create
cmd/testandroid.go:43:12: rewrote os.Open to os.Create with permission not 0666
cmd/testandroid.go: fixed osopen
cmd/testdraw2d.go:45:30: rewrote os.Open with O_CREATE but not O_TRUNC to 
os.Create
cmd/testdraw2d.go:45:12: rewrote os.Open to os.Create with permission not 0666
cmd/testdraw2d.go: fixed osopen
cmd/testgopher.go:43:30: rewrote os.Open with O_CREATE but not O_TRUNC to 
os.Create
cmd/testgopher.go:43:12: rewrote os.Open to os.Create with permission not 0666
cmd/testgopher.go: fixed osopen
cmd/testimage.go:17:30: rewrote os.Open with O_CREATE but not O_TRUNC to 
os.Create
cmd/testimage.go:17:12: rewrote os.Open to os.Create with permission not 0666
cmd/testimage.go: fixed osopen
cmd/testpostscript.go:20:30: rewrote os.Open with O_CREATE but not O_TRUNC to 
os.Create
cmd/testpostscript.go:20:12: rewrote os.Open to os.Create with permission not 
0666
cmd/testpostscript.go: fixed osopen
LICENSE:1:1: expected 'package', found 'IDENT' Copyright
Makefile:2:1: expected 'package', found 'IDENT' include
postscript/interpreter.go: fixed osopen
README:3:1: expected 'package', found 'IDENT' This
krasin@krasin7:~/go/go/src/pkg/draw2d.googlecode.com/hg$ make install
cd draw2d && make install
make[1]: Entering directory 
`/home/krasin/go/go/src/pkg/draw2d.googlecode.com/hg/draw2d'
make[1]: Nothing to be done for `install'.
make[1]: Leaving directory 
`/home/krasin/go/go/src/pkg/draw2d.googlecode.com/hg/draw2d'
cd postscript && make install
make[1]: Entering directory 
`/home/krasin/go/go/src/pkg/draw2d.googlecode.com/hg/postscript'
6g  -o _go_.6 operators_array.go operators_dictionary.go operators_misc.go 
procedure.go interpreter.go operators_conflict.go operators_graphics.go 
operators_relational.go scanner.go operators.go operators_control.go 
operators_math.go operators_stack.go 
rm -f _obj/draw2d.googlecode.com/hg/postscript.a
gopack grc _obj/draw2d.googlecode.com/hg/postscript.a _go_.6 
cp _obj/draw2d.googlecode.com/hg/postscript.a 
"/home/krasin/go/go/pkg/linux_amd64/draw2d.googlecode.com/hg/postscript.a"
make[1]: Leaving directory 
`/home/krasin/go/go/src/pkg/draw2d.googlecode.com/hg/postscript'


```

Original issue reported on code.google.com by `imkra...@gmail.com` on 15 May 2011 at 5:05
